/**
 * Countries in the world.
 * 
 * Data related to the countries in the world, complying ISO 3166-1, ITU-T E.123 and ITU-T E.164 standards.
 * Includes ISO 3166-1 numeric codes, ISO 3166-1 alpha-2 codes, ITU-T calling codes and names in natural language (English, Spanish and Catalan).
 *
 * @author Víctor Díaz <victor@axiomer.com>
 * @website https://victordiaz.me
 * @copyright 2016 Víctor Díaz
 * @license GNU General Public License http://www.gnu.org/licenses/gpl.txt
 * @version 1.0.0
 */

--
-- Structure of the table `countries`
--

CREATE TABLE IF NOT EXISTS `countries` (
	`number` smallint(3) NOT NULL,
	`alpha` char(2) NOT NULL,
	`calling` smallint(3) NOT NULL,
	`name_en` tinytext NOT NULL,
	`name_es` tinytext NOT NULL,
	`name_ca` tinytext NOT NULL,
	PRIMARY KEY (`number`)
	UNIQUE KEY `alpha` (`alpha`)
) DEFAULT CHARSET=utf8mb4 PAGE_CHECKSUM=1;

--
-- Data of the table `emojis`
--

INSERT INTO `countries` (`number`, `alpha`, `calling`, `name_en`, `name_es`, `name_ca`) VALUES
(4, 'af', 93, 'Afghanistan', 'Afganistán', 'Afganistan'),
(8, 'al', 355, 'Albania', 'Albania', 'Albània'),
(10, 'aq', 672, 'Antarctica', 'Antártida', 'Antàrtida'),
(12, 'dz', 213, 'Algeria', 'Argel', 'Algèria'),
(16, 'as', 1, 'American Samoa', 'Samoa Americana', 'Samoa Nord-americana'),
(20, 'ad', 376, 'Andorra', 'Andorra', 'Andorra'),
(24, 'ao', 244, 'Angola', 'Angola', 'Angola'),
(28, 'ag', 1, 'Antigua and Barbuda', 'Antigua y Barbuda', 'Antigua i Barbuda'),
(31, 'az', 994, 'Azerbaijan', 'Azerbaiyán', 'Azerbaidjan'),
(32, 'ar', 54, 'Argentina', 'Argentina', 'Argentina'),
(36, 'au', 61, 'Australia', 'Australia', 'Austràlia'),
(40, 'at', 43, 'Austria', 'Austria', 'Àustria'),
(44, 'bs', 1, 'The Bahamas', 'Bahamas', 'Bahames'),
(48, 'bh', 973, 'Bahrain', 'Baréin', 'Bahrain'),
(50, 'bd', 880, 'Bangladesh', 'Bangladés', 'Bangladesh'),
(51, 'am', 374, 'Armenia', 'Armenia', 'Armènia'),
(52, 'bb', 1, 'Barbados', 'Barbados', 'Barbados'),
(56, 'be', 32, 'Belgium', 'Bélgica', 'Bèlgica'),
(60, 'bm', 1, 'Bermuda', 'Bermudas', 'Bermudes'),
(64, 'bt', 975, 'Bhutan', 'Bután', 'Bhutan'),
(68, 'bo', 591, 'Bolivia', 'Bolivia', 'Bolívia'),
(70, 'ba', 387, 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Bòsnia i Hercegovina'),
(72, 'bw', 267, 'Botswana', 'Botsuana', 'Botswana'),
(74, 'bv', 47, 'Bouvet Island', 'Isla Bouvet', 'Illa Bouvet'),
(76, 'br', 55, 'Brazil', 'Brasil', 'Brasil'),
(84, 'bz', 501, 'Belize', 'Belice', 'Belize'),
(86, 'io', 246, 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'Territori Britànic de l''Oceà Índic'),
(90, 'sb', 677, 'Solomon Islands', 'Islas Salomón', 'Salomó'),
(92, 'vg', 1, 'British Virgin Islands', 'Islas Vírgenes Británicas', 'Illes Verges Britàniques'),
(96, 'bn', 673, 'Brunei', 'Brunéi', 'Brunei'),
(100, 'bg', 359, 'Bulgaria', 'Bulgaria', 'Bulgària'),
(104, 'mm', 95, 'Myanmar', 'Myanmar', 'Myanmar'),
(108, 'bi', 257, 'Burundi', 'Burundi', 'Burundi'),
(112, 'by', 375, 'Belarus', 'Bielorrusia', 'Bielorússia'),
(116, 'kh', 855, 'Cambodia', 'Camboya', 'Cambodja'),
(120, 'cm', 237, 'Cameroon', 'Camerún', 'Camerun'),
(124, 'ca', 1, 'Canada', 'Canadá', 'Canadà'),
(132, 'cv', 238, 'Cabo Verde', 'Cabo Verde', 'Cap Verd'),
(136, 'ky', 1, 'Cayman Islands', 'Islas Caimán', 'Illes Caiman'),
(140, 'cf', 236, 'Central African Republic', 'República Centroafricana', 'República Centreafricana'),
(144, 'lk', 94, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
(148, 'td', 235, 'Chad', 'Chad', 'Txad'),
(152, 'cl', 56, 'Chile', 'Chile', 'Xile'),
(156, 'cn', 86, 'China', 'China', 'Xina'),
(158, 'tw', 886, 'Taiwan', 'Taiwán', 'Taiwan'),
(162, 'cx', 61, 'Christmas Island', 'Isla de Navidad', 'Illa Christmas'),
(166, 'cc', 61, 'Cocos Islands', 'Islas Cocos', 'Illes Cocos'),
(170, 'co', 57, 'Colombia', 'Colombia', 'Colòmbia'),
(174, 'km', 269, 'Comoros', 'Comoras', 'Comores'),
(175, 'yt', 262, 'Mayotte', 'Mayotte', 'Mayotte'),
(178, 'cg', 242, 'Republic of the Congo', 'República del Congo', 'República del Congo'),
(180, 'cd', 243, 'Democratic Republic of the Congo', 'República Democrática del Congo', 'República Democràtica del Congo'),
(184, 'ck', 682, 'Cook Islands', 'Islas Cook', 'Illes Cook'),
(188, 'cr', 506, 'Costa Rica', 'Costa Rica', 'Costa Rica'),
(191, 'hr', 385, 'Croatia', 'Croacia', 'Croàcia'),
(192, 'cu', 53, 'Cuba', 'Cuba', 'Cuba'),
(196, 'cy', 357, 'Cyprus', 'Chipre', 'Xipre'),
(203, 'cz', 420, 'Czech Republic', 'República Checa', 'República Txeca'),
(204, 'bj', 229, 'Benin', 'Benín', 'Benín'),
(208, 'dk', 45, 'Denmark', 'Dinamarca', 'Dinamarca'),
(212, 'dm', 1, 'Dominica', 'Dominica', 'Dominica'),
(214, 'do', 1, 'Dominican Republic', 'República Dominicana', 'República Dominicana'),
(218, 'ec', 593, 'Ecuador', 'Ecuador', 'Equador'),
(222, 'sv', 503, 'El Salvador', 'El Salvador', 'El Salvador'),
(226, 'gq', 240, 'Equatorial Guinea', 'Guinea Ecuatorial', 'Guinea Equatorial'),
(231, 'et', 251, 'Ethiopia', 'Etiopía', 'Etiòpia'),
(232, 'er', 291, 'Eritrea', 'Eritrea', 'Eritrea'),
(233, 'ee', 372, 'Estonia', 'Estonia', 'Estònia'),
(234, 'fo', 298, 'Faroe Islands', 'Islas Feroe', 'Illes Fèroe'),
(238, 'fk', 500, 'Falkland Islands', 'Islas Malvinas', 'Illes Malvines'),
(239, 'gs', 500, 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sandwich del Sur', 'Illes Geòrgia del Sud i Sandwich del Sud'),
(242, 'fj', 679, 'Fiji', 'Fiyi', 'Fiji'),
(246, 'fi', 358, 'Finland', 'Finlandia', 'Finlàndia'),
(248, 'ax', 358, 'Åland Islands', 'Islas Åland', 'Illes Åland'),
(250, 'fr', 33, 'France', 'Francia', 'Frància'),
(254, 'gf', 594, 'French Guiana', 'Guayana Francesa', 'Guaiana Francesa'),
(258, 'pf', 689, 'French Polynesia', 'Polinesia Francesa', 'Polinèsia Francesa'),
(260, 'tf', 33, 'French Southern and Antarctic Lands', 'Tierras Australes y Antárticas Francesas', 'Terres Australs i Antàrtiques Franceses'),
(262, 'dj', 253, 'Djibouti', 'Yibuti', 'Djibouti'),
(266, 'ga', 241, 'Gabon', 'Gabón', 'Gabon'),
(268, 'ge', 995, 'Georgia', 'Georgia', 'Geòrgia'),
(270, 'gm', 220, 'Gambia', 'Gambia', 'Gàmbia'),
(275, 'ps', 970, 'Palestine', 'Palestina', 'Palestina'),
(276, 'de', 49, 'Germany', 'Alemania', 'Alemanya'),
(288, 'gh', 233, 'Ghana', 'Ghana', 'Ghana'),
(292, 'gi', 350, 'Gibraltar', 'Gibraltar', 'Gibraltar'),
(296, 'ki', 686, 'Kiribati', 'Kiribati', 'Kiribati'),
(300, 'gr', 30, 'Greece', 'Grecia', 'Grècia'),
(304, 'gl', 299, 'Greenland', 'Groenlandia', 'Grenlàndia'),
(308, 'gd', 1, 'Grenada', 'Granada', 'Grenada'),
(312, 'gp', 590, 'Guadeloupe', 'Guadalupe', 'Guadalupe'),
(316, 'gu', 1, 'Guam', 'Guam', 'Guam'),
(320, 'gt', 502, 'Guatemala', 'Guatemala', 'Guatemala'),
(324, 'gn', 224, 'Guinea', 'Guinea', 'Guinea'),
(328, 'gy', 592, 'Guyana', 'Guyana', 'Guyana'),
(332, 'ht', 509, 'Haiti', 'Haití', 'Haití'),
(334, 'hm', 61, 'Heard Island and McDonald Islands', 'Islas Heard y McDonald', 'Illes Heard i McDonald'),
(336, 'va', 39, 'Vatican City', 'Ciudad del Vaticano', 'Ciutat del Vaticà'),
(340, 'hn', 504, 'Honduras', 'Honduras', 'Hondures'),
(344, 'hk', 852, 'Hong Kong', 'Hong Kong', 'Hong Kong'),
(348, 'hu', 36, 'Hungary', 'Hungría', 'Hongria'),
(352, 'is', 354, 'Iceland', 'Islandia', 'Islàndia'),
(356, 'in', 91, 'India', 'India', 'Índia'),
(360, 'id', 62, 'Indonesia', 'Indonesia', 'Indonèsia'),
(364, 'ir', 98, 'Iran', 'Irán', 'Iran'),
(368, 'iq', 964, 'Iraq', 'Irak', 'Iraq'),
(372, 'ie', 353, 'Ireland', 'Irlanda', 'Irlanda'),
(376, 'il', 972, 'Israel', 'Israel', 'Israel'),
(380, 'it', 39, 'Italy', 'Italia', 'Itàlia'),
(384, 'ci', 225, 'Ivory Coast', 'Costa de Marfil', 'Costa d''Ivori'),
(388, 'jm', 1, 'Jamaica', 'Jamaica', 'Jamaica'),
(392, 'jp', 81, 'Japan', 'Japón', 'Japó'),
(398, 'kz', 7, 'Kazakhstan', 'Kazajistán', 'Kazakhstan'),
(400, 'jo', 962, 'Jordan', 'Jordania', 'Jordània'),
(404, 'ke', 254, 'Kenya', 'Kenia', 'Kenya'),
(408, 'kp', 850, 'North Korea', 'Corea del Norte', 'Corea del Nord'),
(410, 'kr', 82, 'South Korea', 'Corea del Sur', 'Corea del Sud'),
(414, 'kw', 965, 'Kuwait', 'Kuwait', 'Kuwait'),
(417, 'kg', 996, 'Kyrgyzstan', 'Kirguistán', 'Kirguizistan'),
(418, 'la', 856, 'Laos', 'Laos', 'Laos'),
(422, 'lb', 961, 'Lebanon', 'Líbano', 'Líban'),
(426, 'ls', 266, 'Lesotho', 'Lesoto', 'Lesotho'),
(428, 'lv', 371, 'Latvia', 'Letonia', 'Letònia'),
(430, 'lr', 231, 'Liberia', 'Liberia', 'Libèria'),
(434, 'ly', 218, 'Libya', 'Libia', 'Líbia'),
(438, 'li', 423, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
(440, 'lt', 370, 'Lithuania', 'Lituania', 'Lituània'),
(442, 'lu', 352, 'Luxembourg', 'Luxemburgo', 'Luxemburg'),
(446, 'mo', 853, 'Macau', 'Macao', 'Macau'),
(450, 'mg', 261, 'Madagascar', 'Madagascar', 'Madagascar'),
(454, 'mw', 265, 'Malawi', 'Malaui', 'Malawi'),
(458, 'my', 60, 'Malaysia', 'Malasia', 'Malàisia'),
(462, 'mv', 960, 'Maldives', 'Maldivas', 'Maldives'),
(466, 'ml', 223, 'Mali', 'Malí', 'Mali'),
(470, 'mt', 356, 'Malta', 'Malta', 'Malta'),
(474, 'mq', 596, 'Martinique', 'Martinica', 'Martinica'),
(478, 'mr', 222, 'Mauritania', 'Mauritania', 'Mauritània'),
(480, 'mu', 230, 'Mauritius', 'Mauricio', 'Maurici'),
(484, 'mx', 52, 'Mexico', 'México', 'Mèxic'),
(492, 'mc', 377, 'Monaco', 'Mónaco', 'Mònaco'),
(496, 'mn', 976, 'Mongolia', 'Mongolia', 'Mongòlia'),
(498, 'md', 373, 'Moldova', 'Moldavia', 'Moldàvia'),
(499, 'me', 382, 'Montenegro', 'Montenegro', 'Montenegro'),
(500, 'ms', 1, 'Montserrat', 'Montserrat', 'Montserrat'),
(504, 'ma', 212, 'Morocco', 'Marruecos', 'Marroc'),
(508, 'mz', 258, 'Mozambique', 'Mozambique', 'Moçambic'),
(512, 'om', 968, 'Oman', 'Omán', 'Oman'),
(516, 'na', 264, 'Namibia', 'Namibia', 'Namíbia'),
(520, 'nr', 674, 'Nauru', 'Nauru', 'Nauru'),
(524, 'np', 977, 'Nepal', 'Nepal', 'Nepal'),
(528, 'nl', 31, 'Netherlands', 'Países Bajos', 'Països Baixos'),
(531, 'cw', 599, 'Curaçao', 'Curazao', 'Curaçao'),
(533, 'aw', 297, 'Aruba', 'Aruba', 'Aruba'),
(534, 'sx', 1, 'Sint Maarten', 'Sint Maarten', 'Sint Maarten'),
(535, 'bq', 599, 'Caribbean Netherlands', 'Caribe Neerlandés', 'Carib Neerlandès'),
(540, 'nc', 687, 'New Caledonia', 'Nueva Caledonia', 'Nova Caledònia'),
(548, 'vu', 678, 'Vanuatu', 'Vanuatu', 'Vanuatu'),
(554, 'nz', 64, 'New Zealand', 'Nueva Zelanda', 'Nova Zelanda'),
(558, 'ni', 505, 'Nicaragua', 'Nicaragua', 'Nicaragua'),
(562, 'ne', 227, 'Niger', 'Níger', 'Níger'),
(566, 'ng', 234, 'Nigeria', 'Nigeria', 'Nigèria'),
(570, 'nu', 683, 'Niue', 'Niue', 'Niue'),
(574, 'nf', 672, 'Norfolk Island', 'Isla Norfolk', 'Illa Norfolk'),
(578, 'no', 47, 'Norway', 'Noruega', 'Noruega'),
(580, 'mp', 1, 'Northern Mariana Islands', 'Islas Marianas del Norte', 'Illes Mariannes Septentrionals'),
(581, 'um', 1, 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de Estados Unidos', 'Illes Perifèriques Menors dels EUA'),
(583, 'fm', 691, 'Federated States of Micronesia', 'Estados Federados de Micronesia', 'Estats Federats de Micronèsia'),
(584, 'mh', 692, 'Marshall Islands', 'Islas Marshall', 'Illes Marshall'),
(585, 'pw', 680, 'Palau', 'Palaos', 'Palau'),
(586, 'pk', 92, 'Pakistan', 'Pakistán', 'Pakistan'),
(591, 'pa', 507, 'Panama', 'Panamá', 'Panamà'),
(598, 'pg', 675, 'Papua New Guinea', 'Papúa Nueva Guinea', 'Papua Nova Guinea'),
(600, 'py', 595, 'Paraguay', 'Paraguay', 'Paraguai'),
(604, 'pe', 51, 'Peru', 'Perú', 'Perú'),
(608, 'ph', 63, 'Philippines', 'Filipinas', 'Filipines'),
(612, 'pn', 64, 'Pitcairn Islands', 'Islas Pitcairn', 'Illes Pitcairn'),
(616, 'pl', 48, 'Poland', 'Polonia', 'Polònia'),
(620, 'pt', 351, 'Portugal', 'Portugal', 'Portugal'),
(624, 'gw', 245, 'Guinea-Bissau', 'Guinea-Bisáu', 'Guinea Bissau'),
(626, 'tl', 670, 'East Timor', 'Timor Oriental', 'Timor Oriental'),
(630, 'pr', 1, 'Puerto Rico', 'Puerto Rico', 'Puerto Rico'),
(634, 'qa', 974, 'Qatar', 'Catar', 'Qatar'),
(638, 're', 262, 'Réunion', 'Reunión', 'Reunió'),
(642, 'ro', 40, 'Romania', 'Rumanía', 'Romania'),
(643, 'ru', 7, 'Russia', 'Rusia', 'Rússia'),
(646, 'rw', 250, 'Rwanda', 'Ruanda', 'Ruanda'),
(652, 'bl', 590, 'Saint Barthélemy', 'San Bartolomé', 'Saint Barthélemy'),
(654, 'sh', 290, 'Saint Helena, Ascension and Tristan da Cunha', 'Santa Elena, Ascensión y Tristán de Acuña', 'Santa Helena, Ascensió i Tristan da Cunha'),
(659, 'kn', 1, 'Saint Kitts and Nevis', 'San Cristóbal y Nieves', 'Saint Christopher i Nevis'),
(660, 'ai', 1, 'Anguilla', 'Anguila', 'Anguilla'),
(662, 'lc', 1, 'Saint Lucia', 'Santa Lucía', 'Saint Lucia'),
(663, 'mf', 590, 'Saint Martin', 'San Martín', 'Saint-Martin'),
(666, 'pm', 508, 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'Saint-Pierre i Miquelon'),
(670, 'vc', 1, 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'Saint Vincent i les Grenadines'),
(674, 'sm', 378, 'San Marino', 'San Marino', 'San Marino'),
(678, 'st', 239, 'São Tomé and Príncipe', 'Santo Tomé y Príncipe', 'São Tomé i Príncipe'),
(682, 'sa', 966, 'Saudi Arabia', 'Arabia Saudí', 'Aràbia Saudita'),
(686, 'sn', 221, 'Senegal', 'Senegal', 'Senegal'),
(688, 'rs', 381, 'Serbia', 'Serbia', 'Sèrbia'),
(690, 'sc', 248, 'Seychelles', 'Seychelles', 'Seychelles'),
(694, 'sl', 232, 'Sierra Leone', 'Sierra Leona', 'Sierra Leone'),
(702, 'sg', 65, 'Singapore', 'Singapur', 'Singapur'),
(703, 'sk', 421, 'Slovakia', 'Eslovaquia', 'Eslovàquia'),
(704, 'vn', 84, 'Vietnam', 'Vietnam', 'Vietnam'),
(705, 'si', 386, 'Slovenia', 'Eslovenia', 'Eslovènia'),
(706, 'so', 252, 'Somalia', 'Somalia', 'Somàlia'),
(710, 'za', 27, 'South Africa', 'Sudáfrica', 'Sud-àfrica'),
(716, 'zw', 263, 'Zimbabwe', 'Zimbabue', 'Zimbabwe'),
(724, 'es', 34, 'Spain', 'España', 'Espanya'),
(728, 'ss', 211, 'South Sudan', 'Sudán del Sur', 'Sudan del Sud'),
(729, 'sd', 249, 'Sudan', 'Sudán', 'Sudan'),
(732, 'eh', 212, 'Western Sahara', 'Sahara Occidental', 'Sàhara Occidental'),
(740, 'sr', 597, 'Suriname', 'Surinam', 'Surinam'),
(744, 'sj', 47, 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen', 'Svalbard i Jan Mayen'),
(748, 'sz', 268, 'Swaziland', 'Suazilandia', 'Swazilàndia'),
(752, 'se', 46, 'Sweden', 'Suecia', 'Suècia'),
(756, 'ch', 41, 'Switzerland', 'Suiza', 'Suïssa'),
(760, 'sy', 963, 'Syria', 'Siria', 'Síria'),
(762, 'tj', 992, 'Tajikistan', 'Tayikistán', 'Tadjikistan'),
(764, 'th', 66, 'Thailand', 'Tailandia', 'Tailàndia'),
(768, 'tg', 228, 'Togo', 'Togo', 'Togo'),
(772, 'tk', 690, 'Tokelau', 'Tokelau', 'Tokelau'),
(776, 'to', 676, 'Tonga', 'Tonga', 'Tonga'),
(780, 'tt', 1, 'Trinidad and Tobago', 'Trinidad y Tobago', 'Trinitat i Tobago'),
(784, 'ae', 971, 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Emirats Àrabs Units'),
(788, 'tn', 216, 'Tunisia', 'Túnez', 'Tunísia'),
(792, 'tr', 90, 'Turkey', 'Turquía', 'Turquia'),
(795, 'tm', 993, 'Turkmenistan', 'Turkmenistán', 'Turkmenistan'),
(796, 'tc', 1, 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'Illes Turks i Caicos'),
(798, 'tv', 688, 'Tuvalu', 'Tuvalu', 'Tuvalu'),
(800, 'ug', 256, 'Uganda', 'Uganda', 'Uganda'),
(804, 'ua', 380, 'Ukraine', 'Ucrania', 'Ucraïna'),
(807, 'mk', 389, 'Macedonia', 'Macedonia', 'Macedònia'),
(818, 'eg', 20, 'Egypt', 'Egipto', 'Egipte'),
(826, 'gb', 44, 'United Kingdom', 'Reino Unido', 'Regne Unit'),
(831, 'gg', 44, 'Guernsey', 'Guernsey', 'Guernsey'),
(832, 'je', 44, 'Jersey', 'Jersey', 'Jersey'),
(833, 'im', 44, 'Isle of Man', 'Isla de Man', 'Illa de Man'),
(834, 'tz', 255, 'Tanzania', 'Tanzania', 'Tanzània'),
(840, 'us', 1, 'United States', 'Estados Unidos', 'Estats Units d''Amèrica'),
(850, 'vi', 1, 'United States Virgin Islands', 'Islas Vírgenes de los Estados Unidos', 'Illes Verges Nord-americanes'),
(854, 'bf', 226, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
(858, 'uy', 598, 'Uruguay', 'Uruguay', 'Uruguai'),
(860, 'uz', 998, 'Uzbekistan', 'Uzbekistán', 'Uzbekistan'),
(862, 've', 58, 'Venezuela', 'Venezuela', 'Veneçuela'),
(876, 'wf', 681, 'Wallis and Futuna', 'Wallis y Futuna', 'Wallis i Futuna'),
(882, 'ws', 685, 'Samoa', 'Samoa', 'Samoa'),
(887, 'ye', 967, 'Yemen', 'Yemen', 'Iemen'),
(894, 'zm', 260, 'Zambia', 'Zambia', 'Zàmbia');